OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    Template:
      Count: 3
    Users:
      Count: 0
  - Name: Org2
    Domain: org2.example.com
    Template:
      Count: 3
    Users:
      Count: 0
