OrdererOrgs:
  - Name: Orderer
    Domain: {IP-HOST-1}
PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    Template:
      Count: 3
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.example.com
    Template:
      Count: 3
    Users:
      Count: 1
